# Generated by Django 5.2.4 on 2025-07-19 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Selecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome da Seleção')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa para Avaliação')),
            ],
            options={
                'verbose_name': 'Seleção',
                'verbose_name_plural': 'Seleções',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Candidato')),
                ('inscricao', models.CharField(max_length=50, unique=True, verbose_name='Número de Inscrição')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo/Função')),
                ('requisito', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Nao', 'Não')], max_length=3, null=True, verbose_name='Possui Requisitos para o Cargo')),
                ('avaliacao', models.CharField(blank=True, choices=[('Graduacao', 'Graduação'), ('Especializacao', 'Especialização'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado'), ('Nao possui', 'Não possui')], max_length=15, null=True, verbose_name='Avaliação Curricular')),
                ('justificativa', models.TextField(blank=True, null=True, verbose_name="Justificativa (se 'Não possui')")),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações Adicionais')),
                ('pontuacao', models.IntegerField(default=0, verbose_name='Pontuação')),
                ('data_importacao', models.DateField(auto_now_add=True, verbose_name='Data da Importação')),
                ('data_analisado', models.DateTimeField(blank=True, null=True)),
                ('analisado', models.BooleanField(default=False, verbose_name='Analisado')),
                ('avaliador_analise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_feitas', to=settings.AUTH_USER_MODEL)),
                ('selecao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatos_da_selecao', to='analise_curricular.selecao', verbose_name='Seleção')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'ordering': ['nome', 'cargo'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RG', 'Registro Geral'), ('CPF', 'CPF'), ('Diploma', 'Diploma'), ('Comprovante', 'Comprovante de Experiência'), ('Outro', 'Outro Documento')], max_length=50)),
                ('arquivo', models.FileField(upload_to='candidatos/documentos/%Y/%m/%d/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='analise_curricular.candidato')),
            ],
        ),
    ]
