# Generated by Django 5.1.3 on 2025-07-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Candidato')),
                ('inscricao', models.CharField(max_length=50, unique=True, verbose_name='Número de Inscrição')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo/Função')),
                ('requisito', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Nao', 'Não')], max_length=3, null=True, verbose_name='Possui Requisitos para o Cargo')),
                ('avaliacao', models.CharField(blank=True, choices=[('Especializacao', 'Especialização'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado'), ('Nao possui', 'Não possui')], max_length=15, null=True, verbose_name='Avaliação Curricular')),
                ('justificativa', models.CharField(blank=True, max_length=255, null=True, verbose_name="Justificativa (se 'Não possui')")),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações Adicionais')),
                ('pontuacao', models.IntegerField(default=0, verbose_name='Pontuação')),
                ('data_analise', models.DateField(auto_now_add=True, verbose_name='Data da Análise')),
                ('analisado', models.BooleanField(default=False, verbose_name='Analisado')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'ordering': ['nome', 'cargo'],
            },
        ),
    ]
