# Generated by Django 5.2.4 on 2025-07-12 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise_curricular', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selecao',
            options={'ordering': ['nome'], 'verbose_name': 'Seleção', 'verbose_name_plural': 'Seleções'},
        ),
        migrations.AlterField(
            model_name='candidato',
            name='avaliacao',
            field=models.CharField(blank=True, choices=[('Graduacao', 'Graduação'), ('Especializacao', 'Especialização'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado'), ('Nao possui', 'Não possui')], max_length=15, null=True, verbose_name='Avaliação Curricular'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='justificativa',
            field=models.TextField(blank=True, null=True, verbose_name="Justificativa (se 'Não possui')"),
        ),
        migrations.CreateModel(
            name='DocumentoCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RG', 'Registro Geral'), ('CPF', 'CPF'), ('Diploma', 'Diploma'), ('Comprovante', 'Comprovante de Experiência'), ('Outro', 'Outro Documento')], max_length=50)),
                ('arquivo', models.FileField(upload_to='candidatos/documentos/%Y/%m/%d/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='analise_curricular.candidato')),
            ],
        ),
    ]
