# Generated by Django 5.2.4 on 2025-08-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise_curricular', '0002_formquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='respostas_dinamicas',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='formquestion',
            name='question_type',
            field=models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('select', 'Seleção'), ('checkbox', 'Checkbox'), ('radio', 'Rádio'), ('textarea', 'Caixa de Texto Grande')], max_length=20),
        ),
    ]
