# Generated by Django 5.2.4 on 2025-08-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise_curricular', '0003_candidato_respostas_dinamicas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='avaliacao',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='justificativa',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='requisito',
        ),
        migrations.AddField(
            model_name='candidato',
            name='declarou_deficiencia',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Nao', 'Não')], default='Nao', max_length=3, verbose_name='Declarou que possui deficiência?'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='tipo_deficiencia',
            field=models.TextField(blank=True, null=True, verbose_name='Tipo de Deficiência'),
        ),
    ]
